### PR TITLE
Add support for TvOS

### PR DESCRIPTION
**Pull request by egze**
All works except using CGColor in the `layer do` block.

I disabled
```
tvos/calayer_spec.rb
tvos/layer_layout_spec.rb
```
until it is fixed in Rubymotion.

Sample app provided.

### CODE REVIEW

**Comment by colinta** [comment]
*Awesome*!  Thanks!  @MarkVillacampa you should check this out. :smiley:

Gonna pull locally and run the sample app, otherwise seems good to me!

**Comment by egze** [comment]
I didn't update travis.yml btw. Should I? It will most likely break because of that bug with missing `exit` method.

**Comment by MarkVillacampa** [comment]
Awesome! :)

I have opened an issue in youtrack: http://hipbyte.myjetbrains.com/youtrack/issue/RM-995

Looks good to me as well. Tests passing locally (except for 'exit' which is not supported in tvOS, but we'll fix that :))

**Comment by jamonholmgren** [comment]
This looks great!!

**Comment by egze** [comment]
@MarkVillacampa great! `exit` bug seems to be already documented as well: http://hipbyte.myjetbrains.com/youtrack/issue/RM-980

**Comment by colinta** [comment]
I'll push a new version out later today - but this LGTM!

**Pull request merged**
