### PR TITLE
Add with zindex

### PR DESCRIPTION
**Pull request by dchersey**
Adding documentation for adding subviews dynamically, as well as support for z-ordering options behind, in_front_of and z_index.

### CODE REVIEW

**Comment by colinta** [comment]
Awesome!  Love this.  I might add support for `add UIImageView, :highlight_square, behind: :name`, and have `get(:name)` called automatically.

**Comment by dchersey** [comment]
Yea, good idea! More consistent with the layout API. People could use
nearest, next or previous to disambiguate views if multiple for same id.

I also managed to briefly document my most common use of context in a way
that prevents the need to write a fuller document on tips & trips, although
that is still on my todo list.

I want to share some examples I have of dynamically modifying constraints,
as well as mixing with RMQ to locate views, and removing views.

The longer I put it off, the more/better examples I have :;

Loving working with this gem. Any thoughts on the android support? How far
did you get with it?

**Comment by colinta** [comment]
I did not get very far on Android, I was supposed to work on an Android project, but it never happened :-/  Glad you dig this gem - I do, too!  I was going to start work on a 2.0 version that removed most of the magic in favor of more explicit views (and in that version, `Layout` is a subclass of `UIView/NSView`).  But I doubt it'll move forward; motion-kit 1.0 works well and is more expressive, keeping in the spirit of Ruby.

**Comment by colinta** [comment]
Btw, this is available in 1.1.0, just pushed to rubygems.

**Comment by dchersey** [comment]
Makes sense ... I did take a quick look at the 2.0 version and I have to
say, I prefer the magic :)

**Pull request merged**
